# Generated by Django 6.1 on 2026-08-10 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('outbound_date', models.DateField()),
                ('return_date', models.DateField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('refresh_interval_hours', models.IntegerField(default=12)),
                ('manual_refresh_cooldown_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['outbound_date'],
            },
        ),
        migrations.CreateModel(
            name='EventAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('origin', 'Origin'), ('destination', 'Destination')], max_length=16)),
                ('position', models.IntegerField(default=0, help_text='Organizer display order / default rank')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_uses', to='events.airport')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='events.event')),
            ],
            options={
                'ordering': ['role', 'position'],
                'unique_together': {('event', 'airport', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ParkingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('mode', models.CharField(choices=[('per_day', 'Per day'), ('flat', 'Flat total')], default='per_day', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='events.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('travel_mode', models.CharField(choices=[('undecided', 'Undecided'), ('flying', 'Flying'), ('driving', 'Driving')], default='undecided', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AirportPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='events.eventairport')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_preferences', to='events.participation')),
            ],
            options={
                'unique_together': {('participation', 'airport')},
            },
        ),
    ]
