# Generated by Django 6.1 on 2026-08-10 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return')], default='outbound', max_length=16)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_manual_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_destination', to='events.airport')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_queries', to='events.event')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_origin', to='events.airport')),
            ],
            options={
                'ordering': ['origin__iata_code', 'destination__iata_code'],
                'unique_together': {('event', 'origin', 'destination', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='FlightOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('legs_count', models.IntegerField(default=1)),
                ('total_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('segments', models.JSONField(default=list)),
                ('booking_link', models.URLField(blank=True, max_length=1000)),
                ('provider', models.CharField(default='amadeus', max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('route_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_offers', to='fares.routequery')),
            ],
            options={
                'ordering': ['route_query', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return')], default='outbound', max_length=16)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('booked', 'Booked'), ('confirmed', 'Confirmed')], default='searching', max_length=16)),
                ('flight_number', models.CharField(blank=True, max_length=16)),
                ('flight_date', models.DateField(blank=True, null=True)),
                ('refundable', models.BooleanField(blank=True, null=True)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enrichment', models.JSONField(blank=True, default=dict)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Unverified')], default='pending', max_length=16)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.participation')),
            ],
            options={
                'unique_together': {('participation', 'direction')},
            },
        ),
    ]
