# Generated by Django 5.2.17 on 2026-08-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightoffer',
            name='provider',
            field=models.CharField(default='google_flights', max_length=32),
        ),
    ]
