# Generated by Django 6.1 on 2026-08-10 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_free_seats', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, help_text='Departure point/time, free text.')),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Flat fuel + tolls estimate.', max_digits=10, null=True)),
                ('parking_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional override of the airport default parking price.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='events.eventairport')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='events.participation')),
            ],
        ),
        migrations.CreateModel(
            name='SeatRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return'), ('both', 'Both ways')], default='both', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests', to='carpool.car')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests', to='events.participation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
